name: 📸 Image Builder

on:
  push:
    tags:
    - 'v*'
  workflow_dispatch: {}

jobs:
  image:
    name: Image
    runs-on: ubuntu-latest
    environment: 
      name: dockerhub
      url: https://hub.docker.com/r/kubed/devcontainers
    steps:

    - name: Checkout
      uses: actions/checkout@v5

    - name: Build Image
      uses: kubed-io/actions/build-image@main
      with: 
        push: ${{ startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push' }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: kubed/devcontainers
        